project 'fitness.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fitness' do
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
end
